FROM mysql:5.6 

ENV MYSQL_ROOT_PASSWORD=root

RUN cd /tmp && mkdir scripts

RUN cd /tmp/scripts

ADD createdb.sh /tmp/scripts/createdb.sh
#ADD Dataset.csv /tmp/scripts/Dataset.csv

ADD Dataset.csv /var/lib/mysql-files/Dataset.csv 

ADD createdb.sh /docker-entrypoint-initdb.d